server:
  port: ${port:8989}
book:
  name: 三国演义
  author: 罗贯中

app:
  version: 1.8.0_282

journal:
  name: ${book.name}
spring:
  profiles:
    active: sit


logging:
  level:
    org:
      springframework: trace