spring:
  application:
    name: springboot-all-dynamic-datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MyNewPassword
    url: jdbc:mysql://localhost:3306/db_01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #java.text.SimpleDateFormat
    time-zone: UTC # 和mysql保持一致

