server:
  port: ${port:8989}
book:
  name: 三国演义
  author: 罗贯中

app:
  version: @java.version@

journal:
  name: ${book.name}
spring:
  profiles:
    active: @spring.profiles.active@


logging:
  level:
    org:
      springframework: trace